// src/js/app.js

import { initDrawingCanvas, clearAllLines, getWallCoordinates, setActiveMaterial } from './drawing.js';

// DOM Elements
const imageUpload = document.getElementById('imageUpload');
const jsonUpload = document.getElementById('jsonUpload');
const drawingModal = document.getElementById('drawingModal');
const saveWallsBtn = document.getElementById('saveWallsBtn');

// Material UI Elements
const materialSelector = document.getElementById('materialSelector');
const materialTracker = document.getElementById('activeMaterialTracker');
const matButtons = materialSelector.querySelectorAll('.mat-btn');

const step2Container = document.getElementById('step2-container');
const step3Container = document.getElementById('step3-container');

// State to hold walls globally in the app
let activeWallsData = [];

// UI State Management
function unlockNextSteps() {
    // Remove the classes that grey out and disable clicks
    step2Container.classList.remove('opacity-50', 'pointer-events-none');
    step3Container.classList.remove('opacity-50', 'pointer-events-none');
    
    console.log("UI Unlocked. Active Walls:", activeWallsData);
}

// Handle File Upload
imageUpload.addEventListener('change', function(e) {
    const file = e.target.files[0];
    if (!file) return;

    // Define allowed MIME types for floor plans
    const validImageTypes = ['image/jpeg', 'image/png', 'image/webp'];

    // Check if the uploaded file's type is in our allowed list
    if (!validImageTypes.includes(file.type)) {
        alert("Invalid file type. Please upload a valid image (JPG, PNG, or WEBP).");
        // Clear the input so the user can select a new file
        e.target.value = ''; 
        return; 
    }

    // Enforce maximum file size (attempting to prevent browser lag)
    const maxSizeInBytes = 20 * 1024 * 1024; // 20 MB
    if (file.size > maxSizeInBytes) {
        alert("File is too large. Please upload an image smaller than 20MB.");
        e.target.value = '';
        return;
    }

    const reader = new FileReader();
    reader.onload = function(f) {
        const base64Data = f.target.result;
        // Pass image into the drawing module for rendering
        initDrawingCanvas(base64Data, drawingModal);
    };
    reader.readAsDataURL(file);
    
    // Clear the input after loading so the user can re-upload files as needed
    e.target.value = '';
});

// Handle Material Selection Clicks (Segmented Control)
matButtons.forEach(button => {
    button.addEventListener('click', (e) => {
        const selectedMaterialKey = e.target.getAttribute('data-material');
        
        // Update state in drawing.js and get config
        const config = setActiveMaterial(selectedMaterialKey);
        
        if (config) {
            // Update the Tracking Text Box
            materialTracker.innerHTML = `Currently Drawing: <strong>${config.name}</strong> (Color: <span style="color:${config.color}">■</span>, Thickness: ${config.thickness}px)`;
            
            // Update button visual state (managed via Tailwind rings)
            matButtons.forEach(btn => btn.classList.remove('active', 'ring-2', 'ring-white'));
            e.target.classList.add('active', 'ring-2', 'ring-white');
        }
    });
});

// Clear Lines
clearLinesBtn.addEventListener('click', () => {
    clearAllLines();
});

// Handle JSON Upload (Skip Drawing)
jsonUpload.addEventListener('change', function(e) {
    const file = e.target.files[0];
    if (!file) return;

    if (file.type !== "application/json" && !file.name.endsWith('.json')) {
        alert("Please upload a valid JSON layout file.");
        e.target.value = '';
        return;
    }

    const reader = new FileReader();
    reader.onload = function(f) {
        try {
            const parsedData = JSON.parse(f.target.result);
            
            // Basic validation to ensure it's our layout format
            if (!Array.isArray(parsedData) || (parsedData.length > 0 && !('material' in parsedData[0]))) {
                throw new Error("Invalid format");
            }
            
            activeWallsData = parsedData;
            alert(`Successfully loaded ${activeWallsData.length} walls!`);
            unlockNextSteps();
            
        } catch (error) {
            alert("Error parsing layout file. Ensure it was generated by this simulator.");
            console.error(error);
        }
    };
    reader.readAsText(file);
    e.target.value = ''; // Reset input
});

// Save Walls from the Drawing modal, move on to next steps
saveWallsBtn.addEventListener('click', () => {
    // Extract the wall data from the canvas first!
    activeWallsData = getWallCoordinates();
    
    // Check if they actually drew anything
    if (activeWallsData.length === 0) {
        alert("You haven't drawn any walls!");
        return;
    }
    
    // Convert array to a formatted JSON string
    const jsonString = JSON.stringify(activeWallsData, null, 2);
    
    // Create a Blob and a temporary download link
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;

    // The browser will select the save location for us
    a.download = "wifi_floorplan_layout.json"; // Default file name
    document.body.appendChild(a);

    // Trigger the download to the local system
    a.click();
    
    // Cleanup memory
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Transition the UI
    drawingModal.classList.add('hidden');
    unlockNextSteps(); // Unlock rest of the screen for next steps
});